import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import { UserProvider } from '../context/UserContext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Fantasy Tennis League',
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
     <body className="min-h-screen bg-gray-50">
       <UserProvider>
         <nav className="bg-white p-4 shadow flex space-x-4">
           <Link href="/register" className="text-blue-600">Register</Link>
           <Link href="/login"    className="text-blue-600">Login</Link>
         </nav>
         <main className="p-6">{children}</main>
       </UserProvider>
     </body>
   </html>
  )
}
